### ISSUE TITLE
I couldn‘t repreduce the result

### ISSUE THREAD

**Issue by black-prince222** [dvirginz/DPC#2]
Hello，I try to  use the checkpoints  you provided  to repreducing the results provided in the paper,  but I can't not  repreduce the result。 
Here is the command I wrote:
**python train_point_corr.py --do_train False --gpus 0 --num_data_workers 8 --resume_from_checkpoint ./data/ckpts/shrec_ckpt.ckpt --default_root_dir ./output/** 

According to the  paper,  I should get 15.3% acc at 1% tolerance. But I only get  14.3%.  

Could you tell me why? Thanks

**Comment by itailang** [comment]
Dear @black-prince222,

Thank you for your interest in our work. The accuracy may somewhat change due to the randomness of sampling points from the SHREC shapes.

**Comment by black-prince222** [comment]
I think the code “pytorch_lightning.seed_everything(seed=seed)“  is supposed to ensure the sampling points are the same every time. Right?  Actually, I got the same accuracy no matter how many times I test on shrec_ckpt.ckpt
