### ISSUE TITLE
Missing File: "./data/surreal_template.ply"

### ISSUE THREAD

**Issue by PinkViolet** [dvirginz/DPC#3]
Hi,

First of all, thanks for your great work. It's a really interesting one to work upon. While I  studied the code of this work, I found that there is a file missing if I tried to train the DPC from scratch on the Surreal dataset, referring to [this line of code](https://github.com/dvirginz/DPC/blob/b4ca7c03e5466174aa3f91886ddbfec51efdc4a7/data/point_cloud_db/surreal.py#L91). The 'surreal_template.ply' cannot be found in the data directory. I tried to look up the repository of 3D-CODED, but I did not find the 'surreal_template.ply' file. If you are pleased, could you provide surreal_template.ply in this repository?

**Comment by itailang** [comment]
Dear @PinkViolet,

Thank you for your interest in our work!
The missing file was added to the repository.
