### ISSUE TITLE
About the training of DPC on 230K Surreal datasets

### ISSUE THREAD

**Issue by 2019EPWL** [dvirginz/DPC#5]
Hi, I retrain DPC on the 230k surreal dataset, and the effect is not as good as in the paper, so can you provide the checkpoint of your training on 230k?

**Comment by itailang** [comment]
Dear @2019EPWL,

We provide our trained models under the [ckpts](https://github.com/dvirginz/DPC/tree/main/data/ckpts) folder. I encourage you to use them.
