### ISSUE TITLE
Dataset url

### ISSUE THREAD

**Issue by zhangquanchen** [dvirginz/DPC#7]
Hi, I find this work interesting and  thanks for your contribution.
But I found that the download url of dataset TOSCA ,SMAL,SURREAL... has been out-of-date.
Would you mind providing a new download url. Thanks!

**Comment by itailang** [comment]
Dear @Jankin66,

I appreciate your interest in our work!Please follow the official link of

**Comment by itailang** [comment]
Dear @Jankin66,

I appreciate your interest in our work! Please follow the link to the official website of each dataset. The links are provided in the [README](https://github.com/dvirginz/DPC/blob/main/README.md) file of the repo. Thank you.

**Comment by zhangquanchen** [comment]
Thanks for your replying. But the TOSCA link in README file has been removed. And I found the official website of TOSCA is not available, either. So could you provide it with me in another way. I would greatly appreciate if you could further the give me the dataset you have downloaded before.

**Comment by zhangquanchen** [comment]
I have got the dataset of SMAL,SURREAL,SHREC19 in the website you provide. But still miss the dataset of TOSCA (.mat). I have search many different kinds of website but fail to find the original version. So here ask you to help to provide a new available of downloading the TOSCA.

**Comment by itailang** [comment]
Dear @Jankin66,

Please get in touch with the authors of the TOSCA dataset directly.
